# Introduction

The MBAn program is an accelerated fast pace program that is designed to teach students hard technical and business skills to be able to succeed in a business analyst position. Because of the fast-paced environment, the curriculum can not cover everything. This website is designed to educate MBAn students about effective communication and collaboration in industry. This website is designed to be a resource for incoming and current MBAn students and alumni to assist these individuals with having in-depth knowledge about effective communication and collaboration as well as the detailed methodologies of how to communicate and collaborate effectively amongst team members. 

To provide students with these resources, team 4Ward has conducted interviews and surveys with individuals who are currently working in different industries. Additionally, the team has utilized the Kresge Library resources to find different research studies on effective communication and collaboration. The team has compiled and analyzed this information to create a user-friendly guide that will define and explain the importance of the two topics and then dive deeper into what they look like in the workplace and different types that are utilized. 

