# Networking

In this section, we would talk about networking.Networking is the process of making connections and building relationships. It can help you get more job/ internship opportunities. There are some useful tips for you to start networking.

## Timeline

Systematic Outreach

Have 2 contacts for each of your top 5 companies from your list
Reach out to one person from each company at the same time

– This will seem overwhelming at first but will space out over time

Follow the “3B7” model of timing/tracking your outreach

add image of 3B7

## Alumni

## Recruiters

## How to write professional emails

1. Brief: Less than 75 words

2. Human: Connection goes first

3. Subtle: Request advice & insight, not job assistance

4. Direct: Make your ask in the form of a question

5. Egoless: Over half the word count is about the contact(no ‘about me’)

6. Sincere: Define interest narrowly (“your experience at Company X”) and broadly (“brand management in
the east coast tech space”)

## Using LinkedIn for networking 

## Coffee chat – what to say